language: python
python:
  - "3.5"
before_install:
  - pip install pytest pytest-cov
  - pip install coveralls
install: "pip install -r requirements.txt -r requirements-tests.txt"
script:
      - py.test
after_success:
      - coveralls
